### ISSUE TITLE
The commands like !tag it dont remove my message

### ISSUE THREAD

**Issue by Lorenzo2282953** [Scythe-Anticheat/Scythe-AntiCheat#100]
The commands like !tag it dont remove my message, and it dupe the message when i add a tag
![image](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/123179424/8b9bc035-436d-4138-9872-8aa2156aa171)

_Originally posted by @Lorenzo2282953 in https://github.com/Scythe-Anticheat/Scythe-AntiCheat/discussions/99#discussioncomment-6118607_

**Comment by MrDiamond64** [comment]
This is known issue. 1.20 requires changes to how the command handler works, a side effect is that happening.

**Comment by MrDiamond64** [comment]
This issue has been fixed with Scythe v2.15.0.
