### ISSUE TITLE
Chat is Completely BROKEN

### ISSUE THREAD

**Issue by Justin-City** [Scythe-Anticheat/Scythe-AntiCheat#101]
Hello I own a server named Justin City  today I awoke and found that sythe commands do not disappear when you type them, mutes no longer work, bans no longer work and chat repeats it self 

Here's proof 
![Screenshot_20230608_130845_Minecraft](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/136009073/11eccaab-2d6c-4b0b-ac2a-ea789cb7350a)

I'm typing everything in the screenshot  while being muted and banned please fix this as I had to pull the server until this issue gets resolved.

Thanks,
The Justin City Networking Team

**Comment by Justin-City** [comment]
This only happens when you have a rank

**Comment by MrDiamond64** [comment]
Chat being duplicated is a known bug. The good thing is, other players won't see you typing commands or chat being duplicated.

Could you explain how ban and mute isn't working?

**Comment by Justin-City** [comment]
Hi yes when you ban a player they get kicked they can't see who banned them the length or anything else and they can just rejoin

**Comment by Justin-City** [comment]
And mutes straight up don't register you mute them NOTHING HAPPENS

**Comment by Justin-City** [comment]
We acadently closed this please ignore that

**Comment by MrDiamond64** [comment]
This issue has been fixed with Scythe v2.15.0.
