### ISSUE TITLE
Ban doesnt work

### ISSUE THREAD

**Issue by Lorenzo2282953** [Scythe-Anticheat/Scythe-AntiCheat#105]
WHEN i ban someone it wont work!!! ONLY ERRORS
![IMG_5004](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/123179424/252be2d1-8f99-4708-b1c5-36e0262d876b)
![IMG_5003](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/123179424/07a14169-a582-4bb5-a22f-1db357c4d00e)

**Comment by MrDiamond64** [comment]
Are you on a local world? If so, then "/kick" doesn't work on you.

Because of this, Scythe uses a fallback method which despawns your player entity, thus making you leave the server.

When the host of the world gets kicked this way, the world doesn't save, making everything go back to the last autosave which doesn't have you banned.

**Comment by Lorenzo2282953** [comment]
Yea @MrDiamond64 !
Im not in a world, im on joinable_by_friends SERVER
(Session, server, host playit.gg)
And still doesnt work, so can u help me?

**Comment by Lorenzo2282953** [comment]
@MrDiamond64  ok sorry for new issue, can u fix the bug then? Or dont, is not thath important for me

**Comment by MrDiamond64** [comment]
> @MrDiamond64 ok sorry for new issue, can u fix the bug then? Or dont, is not thath important for me

To fix the bug, i need to replicate it. However, when i test the ban system it works just fine.

**Comment by Lorenzo2282953** [comment]
Ok.

**Comment by Dream23322** [comment]
You said it was a BDS or?

If your on a BDS, some hosting providers could cause the pack to not function correctly, ik that paradox has some issues with aternos.

**Comment by Ziglar1** [comment]
i run a BDS on synology docker and it does not work for me iether, i tried banning ppl for 1 day and they still were able to log in immediately

**Comment by MrDiamond64** [comment]
This issue should now be fixed with commit 07aa5b2
