### ISSUE TITLE
Yea @MrDiamond64 !

### ISSUE THREAD

**Issue by Lorenzo2282953** [Scythe-Anticheat/Scythe-AntiCheat#107]
Yea @MrDiamond64 !
Im not in a world, im on joinable_by_friends SERVER
(Session, server, host playit.gg, made with javascript node.js)
And still doesnt work, so could you help me? Please, its really cool your anti cheats, i just dont want bugs

_Originally posted by @Lorenzo2282953 in https://github.com/Scythe-Anticheat/Scythe-AntiCheat/issues/105#issuecomment-1636897002_

**Comment by Lorenzo2282953** [comment]
I create new issue so u can see the message everywhere to be sure, thanks.

**Comment by MrDiamond64** [comment]
Please do not create new issues for every response. It is completely unnecessary. I get an email, github mobile notification, and a message sent to my discord server for every time a new comment is sent on an issue or a new issue is created. There is no benefit.
