### ISSUE TITLE
Bugs in version 1.20.12

### ISSUE THREAD

**Issue by DjSneijder** [Scythe-Anticheat/Scythe-AntiCheat#108]
Hi, when I add your anticheat to my server, my server sends me the following messages

[2023-07-22 03:55:45:444 ERROR] [Scripting] TypeError: cannot read property 'enabled' of undefined at <anonymous> (main.js:743)

[2023-07-22 03:56:20:205 ERROR] [Scripting] Error: Failed to get property 'typeId' at <anonymous> (main.js:634)

and many more like this

**Comment by MrDiamond64** [comment]
Hi,

The first log means your using a config from an older version with a newer version of Scythe. You will have to reapply any changes you made to the config.

The second log is a known issue. It has been fixed, and an update with the fix will come when the next Minecraft version comes out.

**Comment by DjSneijder** [comment]
i downloaded the latest version and i didn't make any configuration changes

**Comment by MrDiamond64** [comment]
> i downloaded the latest version and i didn't make any configuration changes

I fixed the issue.

**Comment by DjSneijder** [comment]
will you publish it?
