### ISSUE TITLE
Cant set timer on !ban commands on certain cases

### ISSUE THREAD

**Issue by RSChao** [Scythe-Anticheat/Scythe-AntiCheat#110]
Only happens if account has spaces in the username. The account cant be unbanned either

To reproduce:
Join an account with spaces in the username to the world
ban it with a temporary ban (I tried !ban "RSChao 1HM" 30sec since I found no info on tempbans)

Should be perm banned and cant be unbanned

**Comment by MrDiamond64** [comment]
Hi,

When banning someone with spaces in their name, you just need to put the first word. For the player "RSChao 1HM" you can just do the command "!ban RSChao 30s"

However once 2.16.0 comes out this will be changed to support double quotes making the previous command work.
