### ISSUE TITLE
Sythe Just NUCKED our server

### ISSUE THREAD

**Issue by Justin-City-Games-And-More** [Scythe-Anticheat/Scythe-AntiCheat#115]
Sythe Anti-cheat automatically turned on remove command blocks this is a problem because that breaks everything on every server. I don't know how to turn this off without it being on the server.

To reproduce simply have sythe on your server with a command block 

**Expected behavior**
Sythe won't nuke servers

**Additional context**
We recently had a staff memberturn on us and kick our logging bot so maybe they did this in the 5m that the logging bot was offline. If that is true than it means sythe needs an anti-admin abuse system.

**Comment by Justin-City-Games-And-More** [comment]
UPDATE: We we're wrong it was indeed the corrupt admin

But that means scythe need a good permission system

**Comment by MrDiamond64** [comment]
> UPDATE: We we're wrong it was indeed the corrupt admin
> 
> But that means scythe need a good permission system

You can delete the function files for enabling/disabling addition checks (this I kept for backwards compatibly), and you can change who can access certain Scythe commands in the config.js file. Just look for the command and add a tag to the requiredTags array.

**Comment by Justin-City-Games-And-More** [comment]
Thank you

**Comment by Justin-City-Games-And-More** [comment]
> > UPDATE: We we're wrong it was indeed the corrupt admin
> > But that means scythe need a good permission system
> 
> You can delete the function files for enabling/disabling addition checks (this I kept for backwards compatibly), and you can change who can access certain Scythe commands in the config.js file. Just look for the command and add a tag to the requiredTags array.

Thank You we will set this up I do think that scythe should have a ui for this like other anti-cheats
