### ISSUE TITLE
Ban doesn't work

### ISSUE THREAD

**Issue by CyberTek23H2** [Scythe-Anticheat/Scythe-AntiCheat#117]
**Describe the bug**
A clear and concise description of the nature of the bug.

Hi !

**Reproduce**
1. Go to “Manage Players in Admin axis”
2. Click on “*Player nickname”
3. Scroll down to “Ban Player”
4. Check “Permanent ban”
5. Click “Send”
On the player side it’s on the “Server disconnected” screen.

**Expected behaviour**
Permanently ban the player and prevent them from returning

**Screenshot**
If applicable, add screenshots to explain your problem.
![image](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/53036712/2d093106-3c5c-4b5d-bbcc-ed9d49b5b96e)

**Additional context**
I want to ban a player from my Realm but the player just kicks
(and not banned) the problem is that the player can come back right after.

**Comment by MrDiamond64** [comment]
Please look at issue #105

**Comment by GreatNateDev** [comment]
This happened to me a while back it got fixed tho try downloading the world from server enableing experiments and reuploading to server might fix?

**Comment by MrDiamond64** [comment]
This issue should now be fixed with commit 07aa5b2
