### ISSUE TITLE
Obfuscare Ores For X-Ray Check

### ISSUE THREAD

**Issue by dave9123** [Scythe-Anticheat/Scythe-AntiCheat#118]
**Is your feature request related to a problem? Please describe.**
People using automine cheats, it's unfair.

**Describe the solution you'd like**
Obfuscate ore nearby to the player and when the ore is inside the view range of the player, return them and if the player mined the fake ore, flag them.

**Comment by MrDiamond64** [comment]
Unfortunately this feature is nearly impossible to implement without bugs due to the restrictions of the Scripting API.
