### ISSUE TITLE
.spam crashes the game 

### ISSUE THREAD

**Issue by d524342423** [Scythe-Anticheat/Scythe-AntiCheat#12]
hello would be amazing to have a patch for to .spam on horion what it does is repeat a message a bunch of times so if you do .spam manual 1000000 message its gonna repeats it that many times and crashes the game.

**Comment by MrRazamataz** [comment]
When you say crashes the game, do you mean the client or the server?

**Comment by d524342423** [comment]
> When you say crashes the game, do you mean the client or s

> When you say crashes the game, do you mean the client or the server?

Server

**Comment by Justin-City** [comment]
.spam no longer works on horion

**Comment by MrDiamond64** [comment]
> hello would be amazing to have a patch for to .spam on horion what it does is repeat a message a bunch of times so if you do .spam manual 1000000 message its gonna repeats it that many times and crashes the game.

I added an antispam in [this commit](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/commit/1e7150f0d8044d33ed08e03f5caefa7ed8582382).
