### ISSUE TITLE
Anti fly dont work

### ISSUE THREAD

**Issue by IndianBartonka** [Scythe-Anticheat/Scythe-Anticheat#130]
**Describe the bug**
Anti fly dont work corectly when you have enabled `no fall damage` you can fly

**Expected behavior**
Teleport player to gorund or defeating 'no fall damage'

**Screenshots**
![image](https://github.com/Scythe-Anticheat/Scythe-AntiCheat/assets/68228599/63820c65-51d6-42e9-9f88-0335a62d3d79)

**Comment by Dream23322** [comment]
Do you have anticheat OP?
And what fly settings are you using?

**Comment by atfam** [comment]
me to

**Comment by MrDiamond64** [comment]
@atfam Do you have Anti-Fly enabled? If not then just type `!module flyA enabled true`.

This module is disabled by default as anti-flies are difficult to actually get working with minimal false positives.

**Comment by atfam** [comment]
yes

**Comment by atfam** [comment]
yes @MrDiamond64 

Anti flying is on

**Comment by MrDiamond64** [comment]
This issue is no longer applicable due to https://github.com/Scythe-Anticheat/Scythe-Anticheat/issues/142#issuecomment-2197582613
