### ISSUE TITLE
Baritone

### ISSUE THREAD

**Issue by pixo2000** [Scythe-Anticheat/Scythe-AntiCheat#132]
I want people to get flagged when they use baritone on my server

**Comment by MrDiamond64** [comment]
Baritone does not exist on Bedrock Edition, it is exclusive to Minecraft Java.

**Comment by pixo2000** [comment]
lol didnt saw that its for bedrock sry

**Comment by GreatNateDev** [comment]
joepath in horion says otherwise so yes it is a thing and even if it were not it could easily be made

**Comment by MrDiamond64** [comment]
Baritone and Joe Pathfinder are different things.

**Comment by GreatNateDev** [comment]
> Baritone and Joe Pathfinder are different things.

yes i just realized that baritone is a full on bot software and can do things like mining too but theoretically some one could still make a baritone for minecraft bedrock
