### ISSUE TITLE
anti-fly Not working at all v2.23.2

### ISSUE THREAD

**Issue by atfam** [Scythe-Anticheat/Scythe-Anticheat#142]
One my friend Test anti-fly It was on And it was not doing anything It was not flagging him And not doing anything!!!!

He could move around Perfectly @MrDiamond64
Vision of minecraft:
1.21.1

What were we playing on:
realm

What version of anti-Cheat:
v2.23.2

**Comment by MrDiamond64** [comment]
Please do not ping people who have contributed to this repository for no apparent reason. They (except me) are not active with the development of Scythe Anticheat.

**Comment by atfam** [comment]
ok oops

**Comment by atfam** [comment]
Are you going to fix it? bug @MrDiamond64

**Comment by MrDiamond64** [comment]
> Are you going to fix it? bug @MrDiamond64

Yes, I will fix it once I figure out the issue.

**Comment by atfam** [comment]
thank you For Going to try fix the problem.

Thank you for making minecraft bedrock More fun and Better place.

**Comment by atfam** [comment]
Any luck Yet?

**Comment by atfam** [comment]
Any luck Yet? @MrDiamond64

**Comment by MrDiamond64** [comment]
> Any luck Yet? @MrDiamond64

Unfortunately it seems like the method that Scythe uses to detect Fly no longer works after Minecraft 1.21.0. The check working by seeing if your Y velocity was equal to `0.1552` which is the same velocity you get when you walk off a block.

Bedrock Dedicated Server has a feature called Server Authoritative Movement which is used to predict and correct player movement; the purpose is to prevent movement cheats. This feature is what causes the appearance of a player falling up and down when using a cheat fly. This falling side-effect makes the player have the same Y velocity that you get when you fall off a block, which is mostly impossible to get mid-air (except for a few edge cases but those are mostly accounted for).

However it seems like Mojang changed how player velocity or how Server Authoritative Movement works in Minecraft v1.21.0 which rendered this check useless. I'll either have to figure out a new method of detecting fly, or I'll have to completely remove the check from Scythe.

**Comment by atfam** [comment]
Good luck and And can you please try Get it to work @MrDiamond64

**Comment by atfam** [comment]
can you please try Get it to work @MrDiamond64 

And thank you so much For your time
