### ISSUE TITLE
Enable fly mode not working

### ISSUE THREAD

**Issue by atfam** [Scythe-Anticheat/Scythe-Anticheat#143]
Hey it's me
atfam, again

We were testing Flying mode is not working 

We op someone And When told them to get in Fly mode feature And it was not working 

Vision of minecraft:
1.21.1

What were we playing on:
realm

What version of anti-Cheat:
v2.23.2

**Comment by MrDiamond64** [comment]
The `!fly` command requires Education Edition to be enabled in world settings as it relies on the `/ability` command. Do you have that enabled?

**Comment by atfam** [comment]
no Thank you

:)
