### ISSUE TITLE
op Trigger Anti cheat

### ISSUE THREAD

**Issue by atfam** [Scythe-Anticheat/Scythe-Anticheat#144]
hey It's me again
atfam,

Can you make when you op On the anti-Cheat 

Can you make it not to trigger The Anti- cheat

**Comment by MrDiamond64** [comment]
That is already a feature.

You can enable the `disableFlagsFromScytheOp` option in the `config.js` file (https://github.com/Scythe-Anticheat/Scythe-Anticheat/blob/main/scripts/data/config.js#L15) and it will ignore alerts from Scythe-Opped players.
