### ISSUE TITLE
where did Jesus Anti anti went

### ISSUE THREAD

**Issue by atfam** [Scythe-Anticheat/Scythe-Anticheat#147]
see it can do anti Jesus

But I don't see  and is not working

**Comment by MrDiamond64** [comment]
Where did you see Anti-Jesus from? That check has been removed at least two years ago.

**Comment by atfam** [comment]
can you Add it back in?

**Comment by MrDiamond64** [comment]
> can you Add it back in?

There was a reason it was removed, and that is because there were a lot of false-positives that came along with it. It was best if it was removed.

**Comment by atfam** [comment]
ok But A lot of players use it on a server
