### ISSUE TITLE
Not a function scripting (type)error.

### ISSUE THREAD

**Issue by FalkRaft** [Scythe-Anticheat/Scythe-Anticheat#155]
**Description**
Whenever I load up the world with Scythe anticheat v3.0.0 or use /reload, I get a scripting error stating that the function you put on line 50 of script/loader.js doesn’t exist.

**How To Reproduce**
Steps to reproduce the behaviour:
1. Load up MCBE.
2. Load up a world that has Scythe anticheat activated (doesn’t matter if it’s on the top of the BP list).
3. With console logging turned on, you should see a Scythe scripting (type)error.

**Expected Behaviour**
Scythe anticheat should run as normal.

**Screenshots**
![Screenshot 2024-09-18 at 19 56 33](https://github.com/user-attachments/assets/751b31ca-4760-48dc-89bf-e1a48f799eb1)

**Additional context**
- It throws the error even when you repeat the steps multiple times.
- Only throws the error if you’re on Scythe v3.0.0.

**Platforms Tested**
- IPadOS (likely has the same issue on iOS too, and ARM64 architecture).

**Comment by MrDiamond64** [comment]
Thanks for reporting this issue. Can you download the Scythe Beta from https://github.com/Scythe-Anticheat/Scythe-Anticheat/archive/refs/heads/main.zip and see if it fixes this error?

**Comment by GreatNateDev** [comment]
cannot reproduce IOS (dopamine jailbroken) 16.5 iPad 8 wifi world settings: game-mode creative cheats on edu on all experiments on and game version at 1.21.30 or whatever

**Comment by FalkRaft** [comment]
<img width="1126" alt="Screenshot 2024-09-21 at 10 19 45 jpeg" src="https://github.com/user-attachments/assets/ea7fa724-86c6-4b42-992d-c31517022708">

**Description**
I now get an issue when using the custom chat commands, when using Scythe v3.0.0 beta.

**Steps to Reproduce**
1. Load up a world with beta APIs, cheats, and education edition turned on.
2. Type a Scythe command with the prefix ‘!’ in chat.
3. With console logging on, you should see an error.

**Platforms Tested**
- IPad Air M1 with iPadOS 17.6

**Architecture**
- ARM64

**Comment by MrDiamond64** [comment]
> <img alt="Screenshot 2024-09-21 at 10 19 45 jpeg" width="1126" src="https://private-user-images.githubusercontent.com/164064272/369608888-ea7fa724-86c6-4b42-992d-c31517022708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzQyNjAsIm5iZiI6MTcyNjkzMzk2MCwicGF0aCI6Ii8xNjQwNjQyNzIvMzY5NjA4ODg4LWVhN2ZhNzI0LTg2YzYtNGI0Mi05OTJkLWMzMTUxNzAyMjcwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNTUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGNjMjVmYTQ3OWRjMGMxMWUwZDU0ZWQ5OTIzMzUyNzczMTYzMmE3NDZlMzRkMzUyOTZkMTlmYjRlOGJmZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MidXh-Na5APST2bvLnF5bWmGorjGx7QfJqYyTdYEJMQ">
> 
> **Description** I now get an issue when using the custom chat commands, when using Scythe v3.0.0 beta.
> 
> **Steps to Reproduce**
> 
>     1. Load up a world with beta APIs, cheats, and education edition turned on.
> 
>     2. Type a Scythe command with the prefix ‘!’ in chat.
> 
>     3. With console logging on, you should see an error.
> 
> 
> **Platforms Tested**
> 
>     * IPad Air M1 with iPadOS 17.6
> 
> 
> **Architecture**
> 
>     * ARM64

Can you redownload Scythe from the previous link I sent and see if this fixes the issue?

**Comment by FalkRaft** [comment]
It works now! Thanks.

**Comment by GreatNateDev** [comment]
corrupted download?

**Comment by MrDiamond64** [comment]
> corrupted download?

It was a flaw in how Scythe would automatically update the saved config. You can check the commits f12e3d9 and 8b2a0a9 if you would like to know the exact changes.
