### ISSUE TITLE
False Positives with Reach/A

### ISSUE THREAD

**Issue by FalkRaft** [Scythe-Anticheat/Scythe-Anticheat#161]
**Description**
When you hit a llama in Minecraft Bedrock Edition, depending on the gamemode, it will spit back at you. However the anti-cheat doesn't know that the attacking entity was a llama spit instead of the entity itself, leading to a reach false positive.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Load up a world with the latest Scythe BP applied on it.
2. Spawn a llama and go into survival/adventure mode.
3. Attack the llama, move back awway from it, and spam as fast as you can so that you can knock back the llama spit entity back to the llama.
4. You should see the false flag in the chat.

**Expected behaviour**
The reach check will not happen since the llama spit entity is a projectile.

**Video**
https://github.com/user-attachments/assets/23389302-ba65-4150-b2dd-521d2f203326

**Comment by MrDiamond64** [comment]
Thanks for reporting this bug, it has been fixed in commit 0a9fbd3. You can get the updated version of Scythe with this fix [here](https://github.com/Scythe-Anticheat/Scythe-Anticheat/archive/refs/heads/main.zip).
